version: '3.5'

services:

  neo4j-session-8:
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    image: neo4j-3.5.6:aag
    hostname: neo4j-session-8
    container_name: neo4j-session-8
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ${NEO4J_GDB_DATA}:/var/lib/neo4j/data
      - ${NEO4J_GDB_IMPT}:/import
      - ${NEO4J_GDB_LOGS}:/logs
    networks:
      - backend
    environment:
      - NEO4J_AUTH=neo4j/##dis@da2019##
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_http_timeout_connect=60000
      - NEO4J_apoc_http_timeout_read=120000
      - NEO4J_apoc_jobs_pool_num__threads=4
      - NEO4J_apoc_jobs_schedule_num__threads=4

  apollo-server:
    build: ./apollo-server
    hostname: apollo-server
    container_name: apollo-server
    ports:
      - 4000:4000
    networks:
      - frontend
      - backend

  apollo-client:
    build: ./apollo-client
    hostname: apollo-client
    container_name: apollo-client
    ports:
      - 3000:3000
    networks:
      - frontend

networks:
  frontend:
    name: frontend
  backend:
    name: backend
