version: '3.5'

services:

  jotunheimr:
    build:
      context: ./jotunheimr
      dockerfile: Dockerfile
    image: neo4j-3.5.6:aagps
    hostname: jotunheimr
    container_name: jotunheimr
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ${NEO4J_GDB_DATA:-~/neo4j/data}:/data
      - ${NEO4J_GDB_IMPT:-~/neo4j/import}:/var/lib/neo4j/import
      - ${NEO4J_GDB_LOGS:-~/neo4j/logs}:/logs
    networks:
      - mimir
    environment:
      - NEO4J_AUTH=neo4j/##dis@da2019##
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*,graphql.*
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_http_timeout_connect=60000
      - NEO4J_apoc_http_timeout_read=120000
      - NEO4J_apoc_jobs_pool_num__threads=4
      - NEO4J_apoc_jobs_schedule_num__threads=4
      - NEO4J_apoc_spatial_geocode_provider=osm
      - NEO4J_apoc_spatial_geocode_osm_throttle=5000
      - NEO4J_streams_procedures_enable=true
      - NEO4J_streams_source_enabled=true
      # - NEO4J_kafka_zookeeper_connect=zookeeper:2181
      # - NEO4J_kafka_bootstrap_servers=broker:9093
      - NEO4J_streams_sink_enabled=true
      - NEO4J_dbms_unmanaged__extension__classes=org.neo4j.graphql=/graphql

  gungnir:
    build: ./gungnir
    hostname: gungnir
    container_name: gungnir
    ports:
      - 4000:4000
    networks:
      - urd
      - mimir
    depends_on:
      - jotunheimr
    command: ["./wait_for_jotunheimr.sh", "jotunheimr", "npm", "start"]

  gjallarhorn:
    build: ./gjallarhorn
    hostname: gjallarhornx
    container_name: gjallarhorn
    ports:
      - 8000:8000
    networks:
      - urd
      - mimir

  valhalla:
    build: ./valhalla
    hostname: valhalla
    container_name: valhalla
    ports:
      - 3000:3000
    networks:
      - urd

networks:
  urd:
    name: urd
  mimir:
    name: mimir
