---
version: '3'

services:

  neo4j-dwh:
    build:
      context: ./neo4j-dwh
      dockerfile: Dockerfile
    image: neo4j-3.5.6-eaapos:dwh
    depends_on:
      - zookeeper
      - broker
    ports:
      - 7575:7474
      - 7676:7687
    volumes:
      - ${NEO4J_DWH_DATA}:/var/lib/neo4j/data
      - ${NEO4J_DWH_IMPT}:/var/lib/neo4j/import
      - ${NEO4J_DWH_LOGS}:/logs
    environment:
      - NEO4J_AUTH=neo4j/##dis@da2019##
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_http_timeout_connect=60000
      - NEO4J_apoc_http_timeout_read=120000
      - NEO4J_apoc_jobs_pool_num__threads=4
      - NEO4J_apoc_jobs_schedule_num__threads=4
      - NEO4J_apoc_spatial_geocode_provider=osm
      - NEO4J_apoc_spatial_geocode_osm_throttle=5000
      - NEO4j_streams_procedures_enable=true
      - NEO4J_kafka_zookeeper_connect=zookeeper:2181
      - NEO4J_kafka_bootstrap_servers=broker:9093

  neo4j-gdb:
    build:
      context: ./neo4j-gdb
      dockerfile: Dockerfile
    image: neo4j-3.5.6-eaapos:gdb
    depends_on:
      - zookeeper
      - broker
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ${NEO4J_GDB_DATA}:/var/lib/neo4j/data
      - ${NEO4J_GDB_IMPT}:/var/lib/neo4j/import
      - ${NEO4J_GDB_LOGS}:/logs
    environment:
      - NEO4J_AUTH=neo4j/##dis@da2019##
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_http_timeout_connect=60000
      - NEO4J_apoc_http_timeout_read=120000
      - NEO4J_apoc_jobs_pool_num__threads=4
      - NEO4J_apoc_jobs_schedule_num__threads=4
      - NEO4J_apoc_spatial_geocode_provider=osm
      - NEO4J_apoc_spatial_geocode_osm_throttle=5000
      - NEO4j_streams_procedures_enable=true
      - NEO4J_kafka_zookeeper_connect=zookeeper:2181
      - NEO4J_kafka_bootstrap_servers=broker:9093

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  broker:
    image: confluentinc/cp-enterprise-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS=broker:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_METRIC_REPORTERS=io.confluent.metrics.reporter.ConfluentMetricsReporter
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT=zookeeper:2181
      - CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS=1
      - CONFLUENT_METRICS_ENABLE=true
      - CONFLUENT_SUPPORT_CUSTOMER_ID=anonymous

  schema_registry:
    image: confluentinc/cp-schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema_registry
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181

  connect:
    image: confluentinc/cp-kafka-connect
    depends_on:
      - zookeeper
      - broker
      - schema_registry
    ports:
      - "8083:8083"
    volumes:
      - ./plugins:/tmp/connect-plugins
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=broker:9093
      - CONNECT_REST_ADVERTISED_HOST_NAME=connect
      - CONNECT_REST_PORT=8083
      - CONNECT_GROUP_ID=compose-connect-group
      - CONNECT_CONFIG_STORAGE_TOPIC=docker-connect-configs
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_FLUSH_INTERVAL_MS=10000
      - CONNECT_OFFSET_STORAGE_TOPIC=docker-connect-offsets
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_TOPIC=docker-connect-status
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://schema_registry:8081
      - CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://schema_registry:8081
      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_ZOOKEEPER_CONNECT=zookeeper:2181
      - CONNECT_PLUGIN_PATH=/usr/share/java,/tmp/connect-plugins,/usr/share/confluent-hub-components
      - CONNECT_LOG4J_LOGGERS=org.apache.zookeeper=DEBUG,org.I0Itec.zkclient=DEBUG,org.reflections=ERROR

  control-center:
    image: confluentinc/cp-enterprise-control-center
    depends_on:
      - zookeeper
      - broker
      - schema_registry
      - connect
    ports:
      - "9021:9021"
    environment:
      - CONTROL_CENTER_BOOTSTRAP_SERVERS=broker:9093
      - CONTROL_CENTER_ZOOKEEPER_CONNECT=zookeeper:2181
      - CONTROL_CENTER_CONNECT_CLUSTER=connect:8083
      - CONTROL_CENTER_REPLICATION_FACTOR=1
      - CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1
      - CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1
      - CONFLUENT_METRICS_TOPIC_REPLICATION=1
      - PORT=9021
